version: "3.9"

services:
  web:
    build:
      context: .
      args:
        UID: ${UID:-1000}
        GID: ${GID:-1001}
    user: "${UID:-1000}:${GID:-1001}"
    command: bundle exec puma -C config/puma.rb
    entrypoint: ["/bin/bash", "./entrypoint.sh"]
    environment:
      - UID=${UID:-1000}
      - GID=${GID:-1001}
      - BUNDLE_FROZEN=false
    volumes:
      - .:/app:cached
      - .bundle:/app/.bundle
      - bundle_cache:/gems
    ports:
      - "3000:3000"
    env_file: .env
    depends_on:
      - db
      - redis

  sidekiq:
    build:
      context: .
      args:
        UID: ${UID:-1000}
        GID: ${GID:-1001}
    user: "${UID:-1000}:${GID:-1001}"
    command: bundle exec sidekiq
    entrypoint: ["/bin/bash", "./entrypoint.sh"]
    environment:
      - UID=${UID:-1000}
      - GID=${GID:-1001}
      - BUNDLE_FROZEN=false
    volumes:
      - .:/app:cached
      - .bundle:/app/.bundle
      - bundle_cache:/gems
    env_file: .env
    depends_on:
      - db
      - redis

  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

volumes:
  pgdata:
  bundle_cache:
