# 松江市温泉マップ - 開発環境設定
#
# このファイルは開発環境での Rails アプリケーションの動作を制御します
# 設定変更後は docker compose restart web で反映されます

require "active_support/core_ext/integer/time"

Rails.application.configure do
  # config/application.rb の設定よりも優先されます

  # コード変更時の自動リロード（開発効率向上）
  config.enable_reloading = true

  # アプリケーション起動時の一括読み込みを無効化（起動高速化）
  config.eager_load = false

  # エラー発生時に詳細情報を表示（デバッグ用）
  config.consider_all_requests_local = true

  # サーバータイミング情報の表示（パフォーマンス測定用）
  config.server_timing = true

  # Action Controller キャッシュの設定
  # `rails dev:cache` でキャッシュの有効/無効を切り替え可能
  if Rails.root.join("tmp/caching-dev.txt").exist?
    config.action_controller.perform_caching = true
    config.action_controller.enable_fragment_cache_logging = true
    config.public_file_server.headers = { "cache-control" => "public, max-age=#{2.days.to_i}" }
  else
    config.action_controller.perform_caching = false
  end

  # キャッシュストア設定（開発環境では メモリストア を使用）
  config.cache_store = :memory_store

  # Store uploaded files on the local file system (see config/storage.yml for options).
  config.active_storage.service = :local

  # Don't care if the mailer can't send.
  config.action_mailer.raise_delivery_errors = false

  # Make template changes take effect immediately.
  config.action_mailer.perform_caching = false

  # Set localhost to be used by links generated in mailer templates.
  config.action_mailer.default_url_options = { host: "localhost", port: 3000 }

  # Print deprecation notices to the Rails logger.
  config.active_support.deprecation = :log

  # Raise an error on page load if there are pending migrations.
  config.active_record.migration_error = :page_load

  # Highlight code that triggered database queries in logs.
  config.active_record.verbose_query_logs = true

  # Append comments with runtime information tags to SQL queries in logs.
  config.active_record.query_log_tags_enabled = true

  # Highlight code that enqueued background job in logs.
  config.active_job.verbose_enqueue_logs = true

  # Raises error for missing translations.
  # config.i18n.raise_on_missing_translations = true

  # Annotate rendered view with file names.
  config.action_view.annotate_rendered_view_with_filenames = true

  # Uncomment if you wish to allow Action Cable access from any origin.
  # config.action_cable.disable_request_forgery_protection = true

  # Raise error when a before_action's only/except options reference missing actions.
  config.action_controller.raise_on_missing_callback_actions = true

  # Apply autocorrection by RuboCop to files generated by `bin/rails generate`.
  # config.generators.apply_rubocop_autocorrect_after_generate!

  config.assets.digest = true
end
